"""
Ulke -> eczane zinciri eslestirmesi (Java country fonksiyonlarindan cikarildi).
country_chains_for(country) o ulkenin zincirlerini doner.
"""

COUNTRY_CHAINS = {
    "Kazakhistan": ['ALLIANCE', 'AMAZON', 'APTEKA_NIZKIKH_TSEN', 'APTEKA_SO_SKLADA', 'ASNA', 'ATABAY', 'DOBRAYA', 'EUROPHARMA', 'FARMAKOM', 'GG_APTEKA', 'HIPPOKRAT', 'KZ-TSETNAYA', 'OTHERS', 'RAUZA', 'SADYKHAN', 'SALAMAT', 'TSETNAYA', 'VITA', 'ZERDE'],
    "Belarusian": ['APTEKARU_RB', 'APTEKA_GROYP', 'DOCTOR_VREMYA', 'INLEK', 'PLANET_ZDOROVIA'],
    "Uzbekistan": ['DOCTOR_VREMYA', 'OXYMED', 'STU', 'TABLETKA'],
    "Azerbaijan": ['AVROMED', 'AZERIMED', 'BUTA'],
    "Kyrgystan": ['DOCTOR_VREMYA', 'NEMAN', 'PHARMAMIR'],
    "Armenia": ['AKG', 'ALFA_PHARM', 'GEDEON_RIHTER', 'NATALI_PHARM'],
    "Tajikistan": ['DOCTOR_VREMYA', 'OXYMED', 'RAHMAT', 'STU'],
    "Russia": ['A5_', 'AC_SEMEINAYA', 'ALOE', 'APREL', 'APTECNYJ_MIR', 'APTEKA 25', 'APTEKA.RU', 'APTEKA24', 'APTEKA245', 'APTEKA313', 'APTEKARSKIJ_DVOR', 'APTEKA_FORTE', 'APTEKA_GORODA', 'APTEKA_NA_KRASNOM', 'APTEKI_KUBANI', 'APTEKI_STOLICI', 'ASNA', 'AVE', 'AVICENNA', 'A_MEGA', 'BELAYA_APTEKA', 'DEJURNAYA', 'DIALOG', 'DM', 'DOBRAYA_APTEKA', 'DOCTOR_STOLETOV', 'E-APTEKA', 'EDELVES', 'EDIFARM', 'EKONOM', 'EVALAR', 'FARMACEVT_PLYUS', 'FARMADOM', 'FARMAGRANT', 'FARMAIMPEKS', 'FARMAKOPEYKA', 'FARMATON', 'FARMLEND', 'FARMPREPARATI', 'FARM_HAB', 'FIALKA', 'GARMONIYA_ZDOROVIYA', 'GUBERNSKY_APTEK', 'HAMAL', 'IMPLOSIA', 'KALINA_PHARMA', 'KAZANSKY_APTEKI', 'KHABAROVSKAYA_FARMACIA', 'KLASSIKA', 'LAKI-FARMA', 'LEK_OPT_TORG', 'LISTIK', 'MAGNIT', 'MAKSAVIT', 'MEDSI', 'MEGAFARM', 'MELODIJA_ZDOROVJA', 'MELODIYA_ZDOROVIE_KRASNODAR', 'MELODIYA_ZDOROVIE_NOVOSIBIRSK', 'MFO', 'MONASTIREV', 'MOSAPTEKA', 'NAS', 'NAS_NN', 'NEOPHARM', 'NEVIS', 'NIKA', 'NOVAVITA', 'NOVAYAAPTEKA_KALININGRAD', 'OAS', 'OTHERS', 'OVITA', 'OZON', 'PANAZEYA', 'PERVAYA_APTEKA_ARKHANGELSK', 'PERVAYA_POMOSH_BARNAUL', 'PETERBURGSKIYE', 'PHARMAKOR', 'PLANET_ZDOROVYIA', 'PLANET_ZDOROVYIA_SM', 'POLATFARM', 'POLZA.RU', 'PROAPTEKA', 'PURCHASE', 'RADUGA', 'RIFARM', 'RIGLA', 'ROSA', 'RU_DOKTOR_STOLETOV', 'RU_FARMLAND', 'RU_PLANETA_ZDOROVYIA', 'RU_RIIGLA', 'RU_ZOLOTOE_YOBLOKO', 'SAKURA', 'SAMSON_PHARMA', 'SEMEINAYA_APTEKA', 'SERDCE_ROSSII', 'SGA', 'SHAH', 'SHEKSNA', 'SKANDINAVIYA', 'SOLNYSHKO', 'SOS', 'SOSIALNAYA_APTEKA', 'SOSVEZDIE', 'STOCK', 'TSELITEL', 'TVOY_DOCTOR', 'UNIFARMA', 'UNIVERSITETSKIE', 'UNIVERSITETSKY_APTEKI', 'URAZMANOV', 'VALEO', 'VASHA№1', 'VEK_FARMA', 'VEK_JIVI', 'VERTICAL', 'VESNA', 'VESTA', 'VITA+', 'VITAMED', 'VITA_SAMARA', 'VITA_TOMSK', 'VOENTORG', 'VOLGOFARM', 'ZDOROV.RU', 'ZDOROVIY_GOROD', 'ZDOROVOE', 'ZDRAV_CITY', 'ZHIVIKA', 'ZOLOTOE_YABLOKO'],
}


def country_chains_for(country):
    """Bir ulkenin zincirleri. country bos/None ise tum zincirler (birlesik)."""
    if not country:
        allc = set()
        for chains in COUNTRY_CHAINS.values():
            allc.update(chains)
        return sorted(allc)
    return sorted(COUNTRY_CHAINS.get(country, []))
