# Generated by Django 5.1.4 on 2026-08-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="brand",
            field=models.CharField(blank=True, max_length=100, verbose_name="Brand"),
        ),
        migrations.AddField(
            model_name="employee",
            name="country",
            field=models.CharField(blank=True, max_length=100, verbose_name="Country"),
        ),
    ]
