# Generated by Django 5.1.4 on 2026-08-24 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_user_manager"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("VIEW", "Просмотр"),
                            ("CREATE", "Создание"),
                            ("UPDATE", "Изменение"),
                            ("DELETE", "Удаление"),
                            ("REPORT", "Отчёт"),
                            ("UPLOAD", "Загрузка"),
                            ("ACTION", "Действие"),
                        ],
                        default="VIEW",
                        max_length=12,
                        verbose_name="Тип действия",
                    ),
                ),
                (
                    "screen",
                    models.CharField(blank=True, max_length=120, verbose_name="Экран"),
                ),
                ("path", models.CharField(max_length=255, verbose_name="Путь")),
                (
                    "method",
                    models.CharField(blank=True, max_length=8, verbose_name="Метод"),
                ),
                (
                    "detail",
                    models.CharField(blank=True, max_length=255, verbose_name="Детали"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP-адрес"
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Время"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Журнал активности",
                "verbose_name_plural": "Журнал активности",
                "db_table": "accounts_activity_log",
                "ordering": ["-timestamp"],
            },
        ),
    ]
