# Generated by Django 5.1.4 on 2026-09-03 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_activitylog"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="country",
            field=models.CharField(
                blank=True,
                help_text="Kullanicinin ulkesi (bos = kisit yok). is_staff ise tum ulkeler.",
                max_length=45,
                verbose_name="Country",
            ),
        ),
    ]
