# Generated by Django 5.1.4 on 2026-07-31 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Screen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Screen code"
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Display name")),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Description"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Is active"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Menu order"),
                ),
            ],
            options={
                "verbose_name": "Screen",
                "verbose_name_plural": "Screens",
                "db_table": "authorization_screen",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="AccessLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=80, unique=True, verbose_name="Level name"
                    ),
                ),
                ("rank", models.PositiveIntegerField(default=1, verbose_name="Rank")),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Description"
                    ),
                ),
                (
                    "screens",
                    models.ManyToManyField(
                        blank=True,
                        related_name="access_levels",
                        to="authorization.screen",
                        verbose_name="Accessible screens",
                    ),
                ),
            ],
            options={
                "verbose_name": "Access level",
                "verbose_name_plural": "Access levels",
                "db_table": "authorization_access_level",
                "ordering": ["rank", "name"],
            },
        ),
    ]
