# Generated by Django 5.1.4 on 2026-08-03 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EquipmentRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item", models.CharField(max_length=200, verbose_name="Equipment")),
                ("reason", models.TextField(blank=True, verbose_name="Reason")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "На рассмотрении"),
                            ("APPROVED", "Одобрено"),
                            ("REJECTED", "Отклонено"),
                        ],
                        default="PENDING",
                        max_length=10,
                        verbose_name="Status",
                    ),
                ),
                (
                    "decision_comment",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Decision comment"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "decided_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Decided at"
                    ),
                ),
                (
                    "approver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="equipment_approvals",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Approver",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipment_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Requester",
                    ),
                ),
            ],
            options={
                "verbose_name": "Equipment request",
                "verbose_name_plural": "Equipment requests",
                "db_table": "approvals_equipment_request",
                "ordering": ["-created_at"],
            },
        ),
    ]
