# Generated by Django 5.1.4 on 2026-08-05 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("approvals", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipmentrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "На рассмотрении"),
                    ("APPROVED", "Одобрено"),
                    ("REJECTED", "Отклонено"),
                    ("CANCELLED", "Отменено"),
                ],
                default="PENDING",
                max_length=10,
                verbose_name="Status",
            ),
        ),
    ]
