# Generated by Django 5.1.4 on 2026-08-06 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_date", models.DateField(verbose_name="Report date")),
                (
                    "chain_name",
                    models.CharField(max_length=120, verbose_name="Chain name"),
                ),
                ("country", models.CharField(max_length=60, verbose_name="Country")),
                (
                    "product_name",
                    models.CharField(max_length=300, verbose_name="Product name"),
                ),
                (
                    "brand",
                    models.CharField(
                        choices=[
                            ("SOLGAR", "Solgar"),
                            ("BOUNTY", "Nature's Bounty"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=10,
                        verbose_name="Brand",
                    ),
                ),
                (
                    "pharmacy",
                    models.CharField(
                        blank=True, max_length=400, verbose_name="Pharmacy / address"
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=150, verbose_name="City"),
                ),
                ("count", models.IntegerField(default=0, verbose_name="Sales count")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Sales amount",
                    ),
                ),
                (
                    "remaining_count",
                    models.IntegerField(
                        default=0, verbose_name="Remaining stock count"
                    ),
                ),
                (
                    "remaining_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Remaining stock amount",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales_uploads",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Uploaded by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sales record",
                "verbose_name_plural": "Sales records",
                "db_table": "sales_record",
                "ordering": ["-report_date", "chain_name", "product_name"],
                "indexes": [
                    models.Index(
                        fields=["report_date", "chain_name"],
                        name="sales_recor_report__7c386f_idx",
                    ),
                    models.Index(fields=["brand"], name="sales_recor_brand_7c26f0_idx"),
                ],
            },
        ),
    ]
