# Generated by Django 5.1.4 on 2026-08-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChainDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=120,
                        unique=True,
                        verbose_name="Chain / distributor name",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        default="Russia", max_length=60, verbose_name="Country"
                    ),
                ),
                (
                    "orientation",
                    models.CharField(
                        choices=[
                            ("VERTICAL", "Вертикальный"),
                            ("HORIZONTAL", "Горизонтальный"),
                        ],
                        default="VERTICAL",
                        max_length=12,
                        verbose_name="Layout orientation",
                    ),
                ),
                (
                    "column_map",
                    models.JSONField(default=dict, verbose_name="Column mapping"),
                ),
                (
                    "header_search_limit",
                    models.IntegerField(default=30, verbose_name="Header search limit"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
            ],
            options={
                "verbose_name": "Chain definition",
                "verbose_name_plural": "Chain definitions",
                "db_table": "intern_sls_chain_definition",
                "ordering": ["name"],
            },
        ),
    ]
