# Generated by Django 5.1.4 on 2026-08-10 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0002_chaindefinition"),
    ]

    operations = [
        migrations.CreateModel(
            name="BrandDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=80, unique=True, verbose_name="Brand name"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Brand code"
                    ),
                ),
                ("keywords", models.JSONField(default=list, verbose_name="Keywords")),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="Default brand"),
                ),
                ("priority", models.IntegerField(default=100, verbose_name="Priority")),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
            ],
            options={
                "verbose_name": "Brand definition",
                "verbose_name_plural": "Brand definitions",
                "db_table": "intern_sls_brand_definition",
                "ordering": ["priority", "name"],
            },
        ),
    ]
