# Generated by Django 5.1.4 on 2026-08-10 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0003_branddefinition"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DistributorRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "distributor",
                    models.CharField(max_length=120, verbose_name="Distributor"),
                ),
                (
                    "operation_type",
                    models.CharField(
                        choices=[("SALE", "Продажа"), ("STOCK", "Сток")],
                        default="SALE",
                        max_length=10,
                        verbose_name="Operation type",
                    ),
                ),
                ("country", models.CharField(max_length=60, verbose_name="Country")),
                (
                    "begin_date",
                    models.DateField(blank=True, null=True, verbose_name="Begin date"),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="End date"),
                ),
                (
                    "product_name",
                    models.CharField(max_length=300, verbose_name="Product name"),
                ),
                (
                    "product_type",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Product type"
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        choices=[
                            ("SOLGAR", "Solgar"),
                            ("BOUNTY", "Nature's Bounty"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=10,
                        verbose_name="Brand",
                    ),
                ),
                ("count", models.IntegerField(default=0, verbose_name="Count")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=14,
                        verbose_name="Amount",
                    ),
                ),
                (
                    "city",
                    models.CharField(blank=True, max_length=150, verbose_name="City"),
                ),
                (
                    "client",
                    models.CharField(blank=True, max_length=300, verbose_name="Client"),
                ),
                (
                    "legal_address",
                    models.CharField(
                        blank=True, max_length=400, verbose_name="Legal address"
                    ),
                ),
                (
                    "actual_address",
                    models.CharField(
                        blank=True, max_length=400, verbose_name="Actual address"
                    ),
                ),
                (
                    "inn",
                    models.CharField(blank=True, max_length=30, verbose_name="INN"),
                ),
                (
                    "segment",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="Segment"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="distributor_uploads",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Uploaded by",
                    ),
                ),
            ],
            options={
                "verbose_name": "Distributor record",
                "verbose_name_plural": "Distributor records",
                "db_table": "solgar_stk_distributor_record",
                "ordering": ["-begin_date", "distributor", "product_name"],
                "indexes": [
                    models.Index(
                        fields=["distributor", "operation_type"],
                        name="solgar_stk__distrib_0890ff_idx",
                    ),
                    models.Index(
                        fields=["begin_date", "end_date"],
                        name="solgar_stk__begin_d_137a3c_idx",
                    ),
                    models.Index(fields=["brand"], name="solgar_stk__brand_9b6494_idx"),
                ],
            },
        ),
    ]
