# Generated by Django 5.1.4 on 2026-08-10 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0004_distributorrecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="chaindefinition",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("PHARMACY", "Аптечная сеть"),
                    ("DISTRIBUTOR", "Дистрибьютор"),
                ],
                default="PHARMACY",
                max_length=12,
                verbose_name="Source type",
            ),
        ),
    ]
