# Generated by Django 5.1.4 on 2026-08-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0005_chaindefinition_source_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="AddressGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "city_name",
                    models.CharField(max_length=150, verbose_name="City (Cyrillic)"),
                ),
                (
                    "match_key",
                    models.CharField(
                        db_index=True, max_length=150, verbose_name="Match key"
                    ),
                ),
                (
                    "region",
                    models.CharField(blank=True, max_length=120, verbose_name="Region"),
                ),
                (
                    "district",
                    models.CharField(
                        blank=True, max_length=120, verbose_name="District"
                    ),
                ),
                (
                    "country",
                    models.CharField(blank=True, max_length=60, verbose_name="Country"),
                ),
            ],
            options={
                "verbose_name": "Address group",
                "verbose_name_plural": "Address groups",
                "db_table": "solgar_tst_address_group",
                "indexes": [
                    models.Index(
                        fields=["match_key"], name="solgar_tst__match_k_32d30a_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ProductGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_sales_name",
                    models.CharField(max_length=300, verbose_name="Product sales name"),
                ),
                (
                    "match_key",
                    models.CharField(
                        db_index=True, max_length=300, verbose_name="Match key"
                    ),
                ),
                (
                    "main_group",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Product main group"
                    ),
                ),
                (
                    "sub_group",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Product sub group"
                    ),
                ),
            ],
            options={
                "verbose_name": "Product group",
                "verbose_name_plural": "Product groups",
                "db_table": "solgar_tst_product_group",
                "indexes": [
                    models.Index(
                        fields=["match_key"], name="solgar_tst__match_k_f9c934_idx"
                    )
                ],
            },
        ),
    ]
