# Generated by Django 5.1.4 on 2026-08-12 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0006_addressgroup_productgroup"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="addressgroup",
            options={
                "managed": False,
                "verbose_name": "Address group",
                "verbose_name_plural": "Address groups",
            },
        ),
        migrations.AlterModelOptions(
            name="productgroup",
            options={
                "managed": False,
                "verbose_name": "Product group",
                "verbose_name_plural": "Product groups",
            },
        ),
    ]
