# Generated by Django 5.1.4 on 2026-08-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0007_alter_addressgroup_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("status", models.IntegerField(default=1, verbose_name="Status")),
                (
                    "brand",
                    models.CharField(
                        blank=True, max_length=45, null=True, verbose_name="Brand"
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        blank=True, max_length=12, null=True, verbose_name="Country"
                    ),
                ),
                (
                    "area",
                    models.CharField(
                        blank=True, max_length=45, null=True, verbose_name="Area"
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True, max_length=25, null=True, verbose_name="Region"
                    ),
                ),
                (
                    "district",
                    models.CharField(
                        blank=True, max_length=45, null=True, verbose_name="District"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=45, null=True, verbose_name="City"
                    ),
                ),
                (
                    "activeness",
                    models.CharField(
                        blank=True, max_length=12, null=True, verbose_name="Activeness"
                    ),
                ),
                (
                    "medrep",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Marketing staff",
                    ),
                ),
                (
                    "doctor_date",
                    models.CharField(
                        blank=True,
                        max_length=12,
                        null=True,
                        verbose_name="Activation date",
                    ),
                ),
                (
                    "doctor_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Doctor name",
                    ),
                ),
                (
                    "unified_specialty",
                    models.CharField(
                        blank=True,
                        db_column="Unified_specialty",
                        max_length=45,
                        null=True,
                        verbose_name="Unified specialty",
                    ),
                ),
                (
                    "specialty",
                    models.CharField(
                        blank=True,
                        db_column="Specialty",
                        max_length=45,
                        null=True,
                        verbose_name="Specialty",
                    ),
                ),
                (
                    "position_regalia",
                    models.CharField(
                        blank=True,
                        db_column="Position_regalia",
                        max_length=255,
                        null=True,
                        verbose_name="Position / regalia",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=5, null=True, verbose_name="Category"
                    ),
                ),
                (
                    "clinic_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Clinic name",
                    ),
                ),
                (
                    "clinic_name1",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Clinic name (text)",
                    ),
                ),
                (
                    "clinic_status",
                    models.CharField(
                        blank=True,
                        max_length=45,
                        null=True,
                        verbose_name="Clinic status",
                    ),
                ),
                (
                    "clinic_address",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Clinic address",
                    ),
                ),
                (
                    "clinic_count",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Clinic count"
                    ),
                ),
                (
                    "key_person",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Key person"
                    ),
                ),
                (
                    "doctor_tel",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Doctor tel"
                    ),
                ),
                (
                    "doctor_email",
                    models.CharField(
                        blank=True,
                        max_length=45,
                        null=True,
                        verbose_name="Doctor email",
                    ),
                ),
                (
                    "full_address",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Full address",
                    ),
                ),
                (
                    "requested",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Requested address",
                    ),
                ),
                (
                    "building_type",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Building type",
                    ),
                ),
                (
                    "country_code",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Country code",
                    ),
                ),
                (
                    "administrative_area_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Administrative area name",
                    ),
                ),
                (
                    "sub_administrative_area_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Sub administrative area name",
                    ),
                ),
                (
                    "street",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Street"
                    ),
                ),
                (
                    "homenumber",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Home number",
                    ),
                ),
                (
                    "point_y",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Point Y"
                    ),
                ),
                (
                    "point_x",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Point X"
                    ),
                ),
                (
                    "doctor_id",
                    models.IntegerField(
                        blank=True, default=0, null=True, verbose_name="Doctor id"
                    ),
                ),
                (
                    "entry_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Entry date"
                    ),
                ),
                (
                    "entry_user",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Entry user"
                    ),
                ),
            ],
            options={
                "verbose_name": "Doctor",
                "verbose_name_plural": "Doctors",
                "db_table": "doctor_data",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PharmacyBounty",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "country",
                    models.CharField(
                        blank=True, max_length=45, null=True, verbose_name="Country"
                    ),
                ),
                (
                    "area",
                    models.CharField(
                        blank=True, max_length=45, null=True, verbose_name="Area"
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Region"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="City"
                    ),
                ),
                (
                    "city_region",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="City region",
                    ),
                ),
                (
                    "district",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="District"
                    ),
                ),
                (
                    "metro",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Metro"
                    ),
                ),
                (
                    "group_company",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Group company",
                    ),
                ),
                (
                    "subgroup_company",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Subgroup company",
                    ),
                ),
                (
                    "pharmacy_no",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Pharmacy no",
                    ),
                ),
                (
                    "pharmacy_address",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Pharmacy address",
                    ),
                ),
                (
                    "pharmacy_category",
                    models.CharField(
                        blank=True,
                        max_length=5,
                        null=True,
                        verbose_name="Pharmacy category",
                    ),
                ),
                (
                    "assortiment",
                    models.CharField(
                        blank=True, max_length=45, null=True, verbose_name="Assortiment"
                    ),
                ),
                (
                    "pharmacy_type",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Pharmacy type",
                    ),
                ),
                (
                    "promo",
                    models.CharField(
                        blank=True, max_length=45, null=True, verbose_name="Promo"
                    ),
                ),
                (
                    "marketing_staff",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Marketing staff",
                    ),
                ),
                (
                    "pharmacy_response_person",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Pharmacy head name",
                    ),
                ),
                (
                    "pharmacy_tel",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Pharmacy tel",
                    ),
                ),
                (
                    "pharmacy_email",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Pharmacy email",
                    ),
                ),
                (
                    "pharmacy_activeness",
                    models.CharField(
                        blank=True,
                        max_length=45,
                        null=True,
                        verbose_name="Pharmacy activeness",
                    ),
                ),
                (
                    "pharmacy_activation_date",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Activation date",
                    ),
                ),
                (
                    "comments",
                    models.CharField(
                        blank=True,
                        db_column="Comments",
                        max_length=255,
                        null=True,
                        verbose_name="Comments",
                    ),
                ),
                (
                    "marketing_staff_no",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Marketing staff no"
                    ),
                ),
                (
                    "pharmacy_number_sale",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Pharmacy number sale",
                    ),
                ),
                (
                    "found_no",
                    models.IntegerField(blank=True, null=True, verbose_name="Found no"),
                ),
                (
                    "full_address",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Full address",
                    ),
                ),
                (
                    "requested",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Requested"
                    ),
                ),
                (
                    "building_type",
                    models.CharField(
                        blank=True,
                        max_length=45,
                        null=True,
                        verbose_name="Building type",
                    ),
                ),
                (
                    "country_code",
                    models.CharField(
                        blank=True,
                        max_length=45,
                        null=True,
                        verbose_name="Country code",
                    ),
                ),
                (
                    "administrative_area_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Administrative area name",
                    ),
                ),
                (
                    "sub_administrative_area_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Sub administrative area name",
                    ),
                ),
                (
                    "street",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Street"
                    ),
                ),
                (
                    "homenumber",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Home number",
                    ),
                ),
                (
                    "point_y",
                    models.CharField(
                        blank=True, max_length=45, null=True, verbose_name="Point Y"
                    ),
                ),
                (
                    "point_x",
                    models.CharField(
                        blank=True, max_length=45, null=True, verbose_name="Point X"
                    ),
                ),
                (
                    "processed",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Processed"
                    ),
                ),
                (
                    "status",
                    models.IntegerField(blank=True, null=True, verbose_name="Status"),
                ),
                (
                    "pharmacy_id",
                    models.IntegerField(
                        blank=True, default=0, null=True, verbose_name="Pharmacy id"
                    ),
                ),
                (
                    "assortiment1",
                    models.CharField(
                        blank=True,
                        max_length=45,
                        null=True,
                        verbose_name="Assortiment 1 (OBF)",
                    ),
                ),
                (
                    "pharmacy_group",
                    models.CharField(
                        blank=True,
                        max_length=45,
                        null=True,
                        verbose_name="Pharmacy group",
                    ),
                ),
                (
                    "sku",
                    models.IntegerField(
                        blank=True, default=0, null=True, verbose_name="SKU"
                    ),
                ),
                (
                    "cornerNo",
                    models.IntegerField(
                        blank=True,
                        db_column="cornerNo",
                        default=0,
                        null=True,
                        verbose_name="Corner no",
                    ),
                ),
                (
                    "entry_user",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Entry user"
                    ),
                ),
                (
                    "entry_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Entry date"
                    ),
                ),
                (
                    "pharmacist_name_1",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Pharmacist name 1",
                    ),
                ),
                (
                    "pharmacy_home_tel",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Pharmacist 1 tel",
                    ),
                ),
                (
                    "pharmacist_name_2",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Pharmacist name 2",
                    ),
                ),
                (
                    "pharmacy_work_tel",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Pharmacist 2 tel",
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        blank=True,
                        default="BN",
                        max_length=45,
                        null=True,
                        verbose_name="Brand",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pharmacy (Bounty)",
                "verbose_name_plural": "Pharmacies (Bounty)",
                "db_table": "pharmacy_data_bounty",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PharmacySolgar",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "country",
                    models.CharField(
                        blank=True, max_length=45, null=True, verbose_name="Country"
                    ),
                ),
                (
                    "area",
                    models.CharField(
                        blank=True, max_length=45, null=True, verbose_name="Area"
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Region"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="City"
                    ),
                ),
                (
                    "city_region",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="City region",
                    ),
                ),
                (
                    "district",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="District"
                    ),
                ),
                (
                    "metro",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Metro"
                    ),
                ),
                (
                    "group_company",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Group company",
                    ),
                ),
                (
                    "subgroup_company",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Subgroup company",
                    ),
                ),
                (
                    "pharmacy_no",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Pharmacy no",
                    ),
                ),
                (
                    "pharmacy_address",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Pharmacy address",
                    ),
                ),
                (
                    "pharmacy_category",
                    models.CharField(
                        blank=True,
                        max_length=5,
                        null=True,
                        verbose_name="Pharmacy category",
                    ),
                ),
                (
                    "assortiment",
                    models.CharField(
                        blank=True, max_length=45, null=True, verbose_name="Assortiment"
                    ),
                ),
                (
                    "pharmacy_type",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Pharmacy type",
                    ),
                ),
                (
                    "promo",
                    models.CharField(
                        blank=True, max_length=45, null=True, verbose_name="Promo"
                    ),
                ),
                (
                    "marketing_staff",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Marketing staff",
                    ),
                ),
                (
                    "pharmacy_response_person",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Pharmacy head name",
                    ),
                ),
                (
                    "pharmacy_tel",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Pharmacy tel",
                    ),
                ),
                (
                    "pharmacy_email",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Pharmacy email",
                    ),
                ),
                (
                    "pharmacy_activeness",
                    models.CharField(
                        blank=True,
                        max_length=45,
                        null=True,
                        verbose_name="Pharmacy activeness",
                    ),
                ),
                (
                    "pharmacy_activation_date",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Activation date",
                    ),
                ),
                (
                    "comments",
                    models.CharField(
                        blank=True,
                        db_column="Comments",
                        max_length=255,
                        null=True,
                        verbose_name="Comments",
                    ),
                ),
                (
                    "marketing_staff_no",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Marketing staff no"
                    ),
                ),
                (
                    "pharmacy_number_sale",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Pharmacy number sale",
                    ),
                ),
                (
                    "found_no",
                    models.IntegerField(blank=True, null=True, verbose_name="Found no"),
                ),
                (
                    "full_address",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Full address",
                    ),
                ),
                (
                    "requested",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Requested"
                    ),
                ),
                (
                    "building_type",
                    models.CharField(
                        blank=True,
                        max_length=45,
                        null=True,
                        verbose_name="Building type",
                    ),
                ),
                (
                    "country_code",
                    models.CharField(
                        blank=True,
                        max_length=45,
                        null=True,
                        verbose_name="Country code",
                    ),
                ),
                (
                    "administrative_area_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Administrative area name",
                    ),
                ),
                (
                    "sub_administrative_area_name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Sub administrative area name",
                    ),
                ),
                (
                    "street",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Street"
                    ),
                ),
                (
                    "homenumber",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Home number",
                    ),
                ),
                (
                    "point_y",
                    models.CharField(
                        blank=True, max_length=45, null=True, verbose_name="Point Y"
                    ),
                ),
                (
                    "point_x",
                    models.CharField(
                        blank=True, max_length=45, null=True, verbose_name="Point X"
                    ),
                ),
                (
                    "processed",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Processed"
                    ),
                ),
                (
                    "status",
                    models.IntegerField(blank=True, null=True, verbose_name="Status"),
                ),
                (
                    "pharmacy_id",
                    models.IntegerField(
                        blank=True, default=0, null=True, verbose_name="Pharmacy id"
                    ),
                ),
                (
                    "assortiment1",
                    models.CharField(
                        blank=True,
                        max_length=45,
                        null=True,
                        verbose_name="Assortiment 1 (OBF)",
                    ),
                ),
                (
                    "pharmacy_group",
                    models.CharField(
                        blank=True,
                        max_length=45,
                        null=True,
                        verbose_name="Pharmacy group",
                    ),
                ),
                (
                    "sku",
                    models.IntegerField(
                        blank=True, default=0, null=True, verbose_name="SKU"
                    ),
                ),
                (
                    "cornerNo",
                    models.IntegerField(
                        blank=True,
                        db_column="cornerNo",
                        default=0,
                        null=True,
                        verbose_name="Corner no",
                    ),
                ),
                (
                    "entry_user",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Entry user"
                    ),
                ),
                (
                    "entry_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Entry date"
                    ),
                ),
                (
                    "pharmacist_name_1",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Pharmacist name 1",
                    ),
                ),
                (
                    "pharmacy_home_tel",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Pharmacist 1 tel",
                    ),
                ),
                (
                    "pharmacist_name_2",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Pharmacist name 2",
                    ),
                ),
                (
                    "pharmacy_work_tel",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Pharmacist 2 tel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pharmacy (Solgar)",
                "verbose_name_plural": "Pharmacies (Solgar)",
                "db_table": "pharmacy_data_solgar",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PrmAddress",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("country", models.CharField(blank=True, max_length=45)),
                ("area", models.CharField(blank=True, max_length=45)),
                ("district", models.CharField(blank=True, max_length=45)),
                ("region", models.CharField(blank=True, max_length=45)),
                ("city", models.CharField(blank=True, max_length=45)),
                ("county", models.CharField(blank=True, max_length=45)),
            ],
            options={
                "verbose_name": "PRM address",
                "verbose_name_plural": "PRM addresses",
                "db_table": "`solgar_prm`.`prm_sales_addresses`",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PrmMetro",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("status", models.IntegerField(blank=True, null=True)),
                ("city", models.CharField(blank=True, max_length=45)),
                ("metro", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "verbose_name": "PRM metro",
                "verbose_name_plural": "PRM metros",
                "db_table": "`solgar_prm`.`prm_sales_metro`",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DadQuery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "query_name",
                    models.CharField(
                        max_length=120, unique=True, verbose_name="Query name"
                    ),
                ),
                ("query_script", models.TextField(verbose_name="Query script")),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Description"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated at"),
                ),
            ],
            options={
                "verbose_name": "DAD query",
                "verbose_name_plural": "DAD queries",
                "db_table": "intern_sls_dad_query",
                "ordering": ["query_name"],
            },
        ),
        migrations.AlterModelTable(name="addressgroup", table="solgar_address_group",),
        migrations.AlterModelTable(name="productgroup", table="sales_product_group",),
    ]
