# Generated by Django 5.1.4 on 2026-09-07 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0008_doctor_pharmacybounty_pharmacysolgar_prmaddress_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="distributorrecord",
            name="batch_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Yukleme oturumu kimligi (onizleme -> onay gruplama).",
                max_length=40,
                verbose_name="Batch ID",
            ),
        ),
        migrations.AddField(
            model_name="distributorrecord",
            name="is_confirmed",
            field=models.BooleanField(
                db_index=True,
                default=True,
                help_text="False = onizleme taslagi (kaydedilmedi). True = onaylanmis.",
                verbose_name="Is confirmed",
            ),
        ),
    ]
