# Generated by Django 5.1.4 on 2026-09-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0009_distributorrecord_batch_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesrecord",
            name="aptekno",
            field=models.CharField(blank=True, max_length=120, verbose_name="Aptek no"),
        ),
        migrations.AddField(
            model_name="salesrecord",
            name="batch_id",
            field=models.CharField(
                blank=True, db_index=True, max_length=40, verbose_name="Batch ID"
            ),
        ),
        migrations.AddField(
            model_name="salesrecord",
            name="is_confirmed",
            field=models.BooleanField(
                db_index=True, default=True, verbose_name="Is confirmed"
            ),
        ),
        migrations.AddField(
            model_name="salesrecord",
            name="main_group",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Main group"
            ),
        ),
        migrations.AddField(
            model_name="salesrecord",
            name="salesreader",
            field=models.CharField(
                blank=True, max_length=400, verbose_name="Sales reader"
            ),
        ),
        migrations.AddField(
            model_name="salesrecord",
            name="subgroup",
            field=models.CharField(blank=True, max_length=150, verbose_name="Subgroup"),
        ),
    ]
