# Generated by Django 5.1.4 on 2026-09-16 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0010_salesrecord_aptekno_salesrecord_batch_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeocodeSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("dadata", "DaData"), ("yandex", "Yandex")],
                        default="dadata",
                        max_length=20,
                        verbose_name="Провайдер",
                    ),
                ),
                (
                    "dadata_key",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="DaData Key"
                    ),
                ),
                (
                    "dadata_secret",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="DaData Secret"
                    ),
                ),
                (
                    "yandex_key",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Yandex Key"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
            ],
            options={
                "verbose_name": "Geocode ayari",
                "verbose_name_plural": "Geocode ayarlari",
            },
        ),
    ]
